---
name: MkDocs
on:
  workflow_run:
    workflows: ['CI build']
    types:
      - completed
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@4.5.0
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[docs]
      - name: Lint documentation
        run: |
          invoke doc.lint
          invoke doc.test
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@4.5.0
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[docs]
      - name: Perform documentation tests
        run: |
          invoke doc.coverage
          invoke doc.build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@4.5.0
        with:
          python-version: '3.10'
      - name: Lint documentation
        run: |
          python -m doctest README.md examples
